export const mockOrders = [
  {
    id: "1",
    orderId: "Oun - 123 - 7D5T",
    orderType: "Build A Plate",
    date: "Wednesday 5th, October 2025",
    status: "delivered",
    hasIssue: true,
    imageUrl: "/images/food-placeholder.jpg",
    customer: {
      name: "Madu South",
      phone: "09087675645",
      email: "MaduSouthOkechukwu@gmail.com",
      address: "9, Banjo street, opposite tejuosho road, Yaba, Lagos.",
      avatar: "/images/avatar-placeholder.jpg",
    },
    vendor: {
      name: "Iya Bolu",
      phone: "09087675645",
      rating: 4.2,
      reviews: 90,
      address: "23, Adekunle Road, Off Borno Way",
      avatar: "/images/vendor-placeholder.jpg",
    },
    rider: {
      name: "Ahmed Yinka",
      phone: "09087675645",
      rating: 4.2,
      reviews: 40,
      zone: "Yaba, Ikeja Zone",
      avatar: "/images/rider-placeholder.jpg",
    },
    items: [
      { name: "2x wrap of Garri", price: 250, quantity: 2, total: 500 },
      { name: "1x plate of white soup", price: 400, quantity: 1, total: 400 },
      { name: "2x piece of beef", price: 800, quantity: 2, total: 1600 },
    ],
    mealCost: 2500,
    serviceFee: 250,
    deliveryFee: 800,
    totalFee: 3530,
    zone: "Yaba",
  },
  {
    id: "2",
    orderId: "Oun - 124 - 8E6U",
    orderType: "Build A Plate",
    date: "Wednesday 5th, October 2025",
    status: "ongoing",
    hasIssue: true,
    imageUrl: "/images/food-placeholder.jpg",
    customer: {
      name: "Madu South",
      phone: "09087675645",
      email: "MaduSouthOkechukwu@gmail.com",
      address: "9, Banjo street, opposite tejuosho road, Yaba, Lagos.",
      avatar: "/images/avatar-placeholder.jpg",
    },
    vendor: {
      name: "Iya Bolu",
      phone: "09087675645",
      rating: 4.2,
      reviews: 90,
      address: "23, Adekunle Road, Off Borno Way",
      avatar: "/images/vendor-placeholder.jpg",
    },
    rider: {
      name: "Ahmed Yinka",
      phone: "09087675645",
      rating: 4.2,
      reviews: 40,
      zone: "Yaba, Ikeja Zone",
      avatar: "/images/rider-placeholder.jpg",
    },
    items: [
      { name: "2x wrap of Garri", price: 250, quantity: 2, total: 500 },
      { name: "1x plate of white soup", price: 400, quantity: 1, total: 400 },
    ],
    mealCost: 900,
    serviceFee: 100,
    deliveryFee: 500,
    totalFee: 1500,
    zone: "Yaba",
  },
  {
    id: "3",
    orderId: "Oun - 125 - 9F7V",
    orderType: "Build A Plate",
    date: "Wednesday 5th, October 2025",
    status: "delivered",
    hasIssue: false,
    imageUrl: "/images/food-placeholder.jpg",
    customer: {
      name: "Madu South",
      phone: "09087675645",
      email: "MaduSouthOkechukwu@gmail.com",
      address: "9, Banjo street, opposite tejuosho road, Yaba, Lagos.",
      avatar: "/images/avatar-placeholder.jpg",
    },
    vendor: {
      name: "Iya Bolu",
      phone: "09087675645",
      rating: 4.2,
      reviews: 90,
      address: "23, Adekunle Road, Off Borno Way",
      avatar: "/images/vendor-placeholder.jpg",
    },
    rider: {
      name: "Ahmed Yinka",
      phone: "09087675645",
      rating: 4.2,
      reviews: 40,
      zone: "Yaba, Ikeja Zone",
      avatar: "/images/rider-placeholder.jpg",
    },
    items: [
      { name: "2x wrap of Garri", price: 250, quantity: 2, total: 500 },
      { name: "1x plate of white soup", price: 400, quantity: 1, total: 400 },
      { name: "2x piece of beef", price: 800, quantity: 2, total: 1600 },
    ],
    mealCost: 2500,
    serviceFee: 250,
    deliveryFee: 800,
    totalFee: 3530,
    zone: "Yaba",
  },
  {
    id: "4",
    orderId: "Oun - 126 - 0G8W",
    orderType: "Build A Plate",
    date: "Wednesday 5th, October 2025",
    status: "delivered",
    hasIssue: true,
    imageUrl: "/images/food-placeholder.jpg",
    customer: {
      name: "Madu South",
      phone: "09087675645",
      email: "MaduSouthOkechukwu@gmail.com",
      address: "9, Banjo street, opposite tejuosho road, Yaba, Lagos.",
      avatar: "/images/avatar-placeholder.jpg",
    },
    vendor: {
      name: "Iya Bolu",
      phone: "09087675645",
      rating: 4.2,
      reviews: 90,
      address: "23, Adekunle Road, Off Borno Way",
      avatar: "/images/vendor-placeholder.jpg",
    },
    rider: null, // No rider assigned
    items: [
      { name: "2x wrap of Garri", price: 250, quantity: 2, total: 500 },
    ],
    mealCost: 500,
    serviceFee: 50,
    deliveryFee: 300,
    totalFee: 850,
    zone: "Yaba",
  },
  {
    id: "5",
    orderId: "Oun - 127 - 1H9X",
    orderType: "Build A Plate",
    date: "Tuesday 4th, October 2025",
    status: "delivered",
    hasIssue: false,
    imageUrl: "/images/food-placeholder.jpg",
    customer: {
      name: "Madu South",
      phone: "09087675645",
      email: "MaduSouthOkechukwu@gmail.com",
      address: "9, Banjo street, opposite tejuosho road, Yaba, Lagos.",
      avatar: "/images/avatar-placeholder.jpg",
    },
    vendor: {
      name: "Iya Bolu",
      phone: "09087675645",
      rating: 4.2,
      reviews: 90,
      address: "23, Adekunle Road, Off Borno Way",
      avatar: "/images/vendor-placeholder.jpg",
    },
    rider: {
      name: "Ahmed Yinka",
      phone: "09087675645",
      rating: 4.2,
      reviews: 40,
      zone: "Yaba, Ikeja Zone",
      avatar: "/images/rider-placeholder.jpg",
    },
    items: [
      { name: "2x wrap of Garri", price: 250, quantity: 2, total: 500 },
      { name: "1x plate of white soup", price: 400, quantity: 1, total: 400 },
      { name: "2x piece of beef", price: 800, quantity: 2, total: 1600 },
    ],
    mealCost: 2500,
    serviceFee: 250,
    deliveryFee: 800,
    totalFee: 3530,
    zone: "Yaba",
  },
];

export const mockRiders = [
  {
    id: "1",
    name: "Ahmed Yinka",
    phone: "09087675645",
    rating: 4.2,
    reviews: 40,
    zone: "yaba zone",
    status: "active",
    avatar: "/images/rider-placeholder.jpg",
  },
  {
    id: "2",
    name: "Ahmed Yinka",
    phone: "09087675645",
    rating: 4.2,
    reviews: 40,
    zone: "yaba zone",
    status: "active",
    avatar: "/images/rider-placeholder.jpg",
  },
  {
    id: "3",
    name: "Ahmed Yinka",
    phone: "09087675645",
    rating: 4.2,
    reviews: 40,
    zone: "yaba zone",
    status: "active",
    avatar: "/images/rider-placeholder.jpg",
  },
];